//# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
//  Generated by SAP Cloud Platform Android SDK 2.1.1, on Sun May 26 21:53:19 CEST 2019
//  Proxy Generator Version: 18.11.0-9ee469-20181119

package com.sap.stepbystep.ESPM;

public class PurchaseOrderHeader extends com.sap.cloud.mobile.odata.EntityValue implements android.os.Parcelable {
    public static final android.os.Parcelable.Creator<PurchaseOrderHeader> CREATOR = new android.os.Parcelable.Creator<PurchaseOrderHeader>() {
        public PurchaseOrderHeader createFromParcel(android.os.Parcel in) {
            com.sap.cloud.mobile.odata.JsonEntityProvider provider = com.sap.cloud.mobile.odata.JsonEntityProvider.withMetadata(ESPMContainerMetadata.document);
            ESPMContainer service = new ESPMContainer(provider);
            com.sap.cloud.mobile.odata.DataQuery query = com.sap.cloud.mobile.odata.FromJSON.entity(in.readString());
            query.setEntitySet(ESPMContainerMetadata.EntitySets.purchaseOrderHeaders);
            query.setEntityType(ESPMContainerMetadata.EntityTypes.purchaseOrderHeader);
            com.sap.cloud.mobile.odata.EntityValue entity = service.executeQuery(query).getRequiredEntity();
            return (PurchaseOrderHeader)entity;
        }

        public PurchaseOrderHeader[] newArray(int size) {
            return new PurchaseOrderHeader[size];
        }
    };

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(com.sap.cloud.mobile.odata.ToJSON.entity(this, com.sap.cloud.mobile.odata.DataContext.FULL_METADATA));
    }

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property currencyCode = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderHeader.getProperty("CurrencyCode");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property grossAmount = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderHeader.getProperty("GrossAmount");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property netAmount = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderHeader.getProperty("NetAmount");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property purchaseOrderID = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderHeader.getProperty("PurchaseOrderId");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property supplierID = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderHeader.getProperty("SupplierId");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property taxAmount = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderHeader.getProperty("TaxAmount");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property items = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderHeader.getProperty("Items");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property supplierDetails = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderHeader.getProperty("SupplierDetails");

    /**
     ** See <a href='#PurchaseOrderHeader-boolean-'>PurchaseOrderHeader(boolean)</a>.
     **/
    public PurchaseOrderHeader() {
        this(true);
    }

    public PurchaseOrderHeader(final boolean withDefaults) {
        super(withDefaults, com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderHeader);
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.stepbystep.ESPM.PurchaseOrderHeader copy() {
        return com.sap.stepbystep.ESPM.internal.Any_as_com_sap_stepbystep_ESPM_PurchaseOrderHeader.cast(this.copyEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCurrencyCode() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.currencyCode));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getGrossAmount() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.grossAmount));
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.sap.stepbystep.ESPM.@org.jetbrains.annotations.NotNull PurchaseOrderItem> getItems() {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.sap.stepbystep.ESPM.PurchaseOrderItem>convert(com.sap.cloud.mobile.odata.EntityValueList.castRequired(this.getRequiredValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.items)).toGeneric());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getNetAmount() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.netAmount));
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.stepbystep.ESPM.PurchaseOrderHeader getOld() {
        return com.sap.stepbystep.ESPM.internal.Any_as_com_sap_stepbystep_ESPM_PurchaseOrderHeader.cast(this.getOldEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getPurchaseOrderID() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.purchaseOrderID));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.stepbystep.ESPM.Supplier getSupplierDetails() {
        return com.sap.stepbystep.ESPM.internal.Any_asNullable_com_sap_stepbystep_ESPM_Supplier.cast(this.getOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.supplierDetails));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getSupplierID() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.supplierID));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getTaxAmount() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.taxAmount));
    }

    /**
     ** {@inheritDoc}
     **/
    @java.lang.Override public boolean isProxy() {
        return true;
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityKey key(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String purchaseOrderID) {
        return new com.sap.cloud.mobile.odata.EntityKey().with("PurchaseOrderId", com.sap.cloud.mobile.odata.StringValue.ofNullable(purchaseOrderID));
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.sap.stepbystep.ESPM.@org.jetbrains.annotations.NotNull PurchaseOrderHeader> list(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityValueList from) {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.sap.stepbystep.ESPM.PurchaseOrderHeader>convert(from.toGeneric());
    }

    public void setCurrencyCode(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.currencyCode, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setGrossAmount(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.grossAmount, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setItems(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.sap.stepbystep.ESPM.@org.jetbrains.annotations.NotNull PurchaseOrderItem> value) {
        com.sap.stepbystep.ESPM.PurchaseOrderHeader.items.setEntityList(this, com.sap.cloud.mobile.odata.EntityValueList.from(com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.stepbystep.ESPM.PurchaseOrderItem,com.sap.cloud.mobile.odata.EntityValue>convert(value)));
    }

    public void setNetAmount(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.netAmount, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setPurchaseOrderID(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.purchaseOrderID, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setSupplierDetails(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.stepbystep.ESPM.Supplier value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.supplierDetails, value);
    }

    public void setSupplierID(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.supplierID, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setTaxAmount(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.PurchaseOrderHeader.taxAmount, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }
}
