//# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
//  Generated by SAP Cloud Platform Android SDK 2.1.1, on Sun May 26 21:53:19 CEST 2019
//  Proxy Generator Version: 18.11.0-9ee469-20181119

package com.sap.stepbystep.ESPM;

public class Stock extends com.sap.cloud.mobile.odata.EntityValue implements android.os.Parcelable {
    public static final android.os.Parcelable.Creator<Stock> CREATOR = new android.os.Parcelable.Creator<Stock>() {
        public Stock createFromParcel(android.os.Parcel in) {
            com.sap.cloud.mobile.odata.JsonEntityProvider provider = com.sap.cloud.mobile.odata.JsonEntityProvider.withMetadata(ESPMContainerMetadata.document);
            ESPMContainer service = new ESPMContainer(provider);
            com.sap.cloud.mobile.odata.DataQuery query = com.sap.cloud.mobile.odata.FromJSON.entity(in.readString());
            query.setEntitySet(ESPMContainerMetadata.EntitySets.stock);
            query.setEntityType(ESPMContainerMetadata.EntityTypes.stock);
            com.sap.cloud.mobile.odata.EntityValue entity = service.executeQuery(query).getRequiredEntity();
            return (Stock)entity;
        }

        public Stock[] newArray(int size) {
            return new Stock[size];
        }
    };

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(com.sap.cloud.mobile.odata.ToJSON.entity(this, com.sap.cloud.mobile.odata.DataContext.FULL_METADATA));
    }

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property lotSize = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.stock.getProperty("LotSize");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property minStock = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.stock.getProperty("MinStock");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property productID = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.stock.getProperty("ProductId");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property quantity = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.stock.getProperty("Quantity");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property quantityLessMin = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.stock.getProperty("QuantityLessMin");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property updatedTimestamp = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.stock.getProperty("UpdatedTimestamp");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property productDetails = com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.stock.getProperty("ProductDetails");

    /**
     ** See <a href='#Stock-boolean-'>Stock(boolean)</a>.
     **/
    public Stock() {
        this(true);
    }

    public Stock(final boolean withDefaults) {
        super(withDefaults, com.sap.stepbystep.ESPM.ESPMContainerMetadata.EntityTypes.stock);
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.stepbystep.ESPM.Stock copy() {
        return com.sap.stepbystep.ESPM.internal.Any_as_com_sap_stepbystep_ESPM_Stock.cast(this.copyEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getLotSize() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.Stock.lotSize));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getMinStock() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.Stock.minStock));
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.stepbystep.ESPM.Stock getOld() {
        return com.sap.stepbystep.ESPM.internal.Any_as_com_sap_stepbystep_ESPM_Stock.cast(this.getOldEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.stepbystep.ESPM.Product getProductDetails() {
        return com.sap.stepbystep.ESPM.internal.Any_asNullable_com_sap_stepbystep_ESPM_Product.cast(this.getOptionalValue(com.sap.stepbystep.ESPM.Stock.productDetails));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getProductID() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.Stock.productID));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getQuantity() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.Stock.quantity));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable Boolean getQuantityLessMin() {
        return com.sap.cloud.mobile.odata.BooleanValue.toNullable(this.getOptionalValue(com.sap.stepbystep.ESPM.Stock.quantityLessMin));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime getUpdatedTimestamp() {
        return com.sap.cloud.mobile.odata.LocalDateTime.castOptional(this.getOptionalValue(com.sap.stepbystep.ESPM.Stock.updatedTimestamp));
    }

    /**
     ** {@inheritDoc}
     **/
    @java.lang.Override public boolean isProxy() {
        return true;
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityKey key(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String productID) {
        return new com.sap.cloud.mobile.odata.EntityKey().with("ProductId", com.sap.cloud.mobile.odata.StringValue.ofNullable(productID));
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.sap.stepbystep.ESPM.@org.jetbrains.annotations.NotNull Stock> list(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityValueList from) {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.sap.stepbystep.ESPM.Stock>convert(from.toGeneric());
    }

    public void setLotSize(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.Stock.lotSize, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setMinStock(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.Stock.minStock, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setProductDetails(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.stepbystep.ESPM.Product value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.Stock.productDetails, value);
    }

    public void setProductID(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.Stock.productID, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setQuantity(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.Stock.quantity, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setQuantityLessMin(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable Boolean value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.Stock.quantityLessMin, com.sap.cloud.mobile.odata.BooleanValue.ofNullable(value));
    }

    public void setUpdatedTimestamp(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime value) {
        this.setOptionalValue(com.sap.stepbystep.ESPM.Stock.updatedTimestamp, value);
    }
}
